#include<iostream>
#include<cstdio>
#define int long long
#define M 1000000007
#define i2 500000004
using namespace std;
struct ljb{
	int en,v[2000001],fst[500001],nxt[2000001];
	inline void add(int x,int y)
	{
		en++;
		v[en]=y;
		nxt[en]=fst[x];
		fst[x]=en;
	}
};
ljb t;
int n,m,sz[500001],dp[500001][3];
inline void dfs(int x,int f)
{
	dp[x][2]=2;
	for(int i=t.fst[x];i;i=t.nxt[i])
	{
		int s=t.v[i];
		if(s!=f)
		{
			dfs(s,x);
			dp[x][2]=(i2*dp[x][2]%M*dp[s][2]+i2*dp[x][2])%M;
			dp[x][1]=(dp[x][1]+dp[s][1]-dp[s][2]*i2%M-i2+2*M)%M;
		}
	}
	dp[x][1]=(dp[x][1]+dp[x][2])%M;
}
signed main()
{
	freopen("barrack.in","r",stdin);
	freopen("barrack.out","w",stdout);
	cin>>n>>m;
	for(int i=1;i<=m;i++)
	{
		int x,y;
		scanf("%lld%lld",&x,&y);
		t.add(x,y);
		t.add(y,x);
	}
	if(m==n-1)
	{
		dfs(1,0);
	/*	for(int i=1;i<=n;i++)
			cout<<dp[i][1]*2%M<<' '<<dp[i][2]*2%M<<endl;*/
		int ans=(dp[1][1]-1+M)%M;
		for(int i=1;i<=n-1;i++) ans=(ans*2)%M;
		cout<<ans;
	}
	else
	{
		int ans=1;
		for(int i=1;i<=n;i++)
			ans=(ans*2)%M;
		ans=(ans-1+M)%M;
		for(int i=1;i<=m;i++)
			ans=(ans*2)%M;
		cout<<ans;
	}
	return 0;
}/*
9 8
1 2
1 3
1 4
3 5
3 6
6 7
6 8
4 9*/
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP 
//I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP I AK NOIP #define I Register int
